---

- name: Install dependencies for Ansible apt* modules
  command: apt-get -y install python3-apt
  args:
    warn: no
  register: telegraf_apt_dependencies_installed
  changed_when: "'is already the newest version' not in telegraf_apt_dependencies_installed.stdout"
  tags:
    - telegraf-repository-key
    - telegraf-repository

- name: Add InfluxData repository key
  apt_key:
    url: "{{ telegraf.apt_key_url }}"
    state: present
  tags:
    - telegraf-repository-key
    - telegraf-repository

- name: Install python-pycurl to make apt_repository module workable
  apt: pkg=python3-pycurl
  tags:
    - telegraf-repository

- name: Add InfluxData repository
  apt_repository:
    filename="{{ telegraf.apt_repository_filename }}"
    repo="{{ telegraf.apt_repository }}"
    state=present
    update_cache=yes
  tags:
    - telegraf-repository

- name: Install telegraf
  apt: pkg=telegraf
  notify: telegraf-restart

- name: Add user telegraf to given groups to be able read some stat
  user:
    name: "{{ telegraf.user }}"
    group: "{{ telegraf.group }}"
    groups: "{{ telegraf.groups }}"
    update_password: on_create
