---

- name: Install dependencies for Ansible apt* modules
  command: apt-get -y install python-apt aptitude
  register: telegraf_apt_dependencies_installed
  changed_when: "'is already the newest version' not in telegraf_apt_dependencies_installed.stdout"

- name: Add InfluxData repository key
  apt_key:
    url: "{{ telegraf.apt_key_url }}"
    state: present

- name: Install python-pycurl to make apt_repository module workable
  apt: pkg=python-pycurl

- name: Add InfluxData repository
  apt_repository:
    repo="{{ telegraf.apt_repository }}"
    state=present
    update_cache=yes

- name: Install telegraf
  apt: pkg=telegraf
  notify: telegraf-start

- name: Add user telegraf to given groups to be able read some stat
  user:
    name: "{{ telegraf.user }}"
    group: "{{ telegraf.group }}"
    groups: "{{ telegraf.groups }}"
    update_password: on_create
